name: Build and deploy Python app to Azure Web App - nuhack-ctf-platform

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout application repository
        uses: actions/checkout@v4

      - name: Clone data repository
        run: |
          git clone --recurse-submodules -j8 https://CaptureTheFrog:${{ secrets.EVENT_REPO_PAT }}@github.com/NUHack-Newcastle/nuhack-alpha-2024.git event

      # Rest of your build steps go here...

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_13676A1A9D054BF19C499115C2DB4032 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C8A6AD8B81A245E48AB700F8774D8132 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_977D10A6D9E747FAAEAED23368E6D3B2 }}

      - name: Pull updates from data repository
        run: |
          cd event
          git pull origin main

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'nuhack-ctf-platform'
          slot-name: 'Production'
